export const shopCategories = [
  { id: "complexion", label: "Complexion & face" },
  { id: "eyes", label: "Eyes" },
  { id: "lips", label: "Lips & tips" },
  { id: "skincare", label: "Skin & care" },
  { id: "kits", label: "Makeup kits" },
  { id: "accessories", label: "Cosmetic bags" },
  { id: "extras", label: "Glitter & extras" },
] as const;

export type CatalogCategory = (typeof shopCategories)[number]["id"];
export type CatalogFilter = "all" | CatalogCategory;

export type CatalogProduct = {
  id: string;
  name: string;
  category: CatalogCategory;
  price: number;
  description: string;
};

export const products: CatalogProduct[] = [
  {
    id: "1",
    name: "Liquid Jojoba",
    category: "complexion",
    price: 15,
    description: "Sheer, water-based coverage that blends easily; listed for normal-to-dry skin types.",
  },
  {
    id: "3",
    name: "Creme Foundation",
    category: "complexion",
    price: 25,
    description: "A cream foundation from the original complexion collection. Ask about current shades and availability.",
  },
  {
    id: "4",
    name: "Wet/Dry Powder Foundation",
    category: "complexion",
    price: 25,
    description: "Apply wet for creamy coverage or dry for a matte finish; listed for normal-to-oily skin types.",
  },
  {
    id: "5",
    name: "Matte Finish",
    category: "complexion",
    price: 25,
    description: "Hydrating, oil-free coverage with cucumber extract; the original listing describes it as suitable for all skin types.",
  },
  {
    id: "7",
    name: "Camouflage Cremes",
    category: "complexion",
    price: 10,
    description: "A smooth-textured cream for concealing or highlighting areas of the face.",
  },
  {
    id: "8",
    name: "Corrective Cover Cremes",
    category: "complexion",
    price: 10,
    description: "A coverage cream listed for its smooth texture. Contact Saint James for shade details.",
  },
  {
    id: "9",
    name: "Cover Sticks",
    category: "complexion",
    price: 10,
    description: "A convenient cover stick for targeted concealing and touch-ups.",
  },
  {
    id: "10",
    name: "All Around Cover",
    category: "complexion",
    price: 25,
    description: "Neutral and corrective colors are packaged together to simplify finding a balanced coverage shade.",
  },
  {
    id: "11",
    name: "Under Makeup Tint & Highlighter",
    category: "complexion",
    price: 30,
    description: "Color perfectors help even the look of skin tone; highlighters bring a soft, subtle glow.",
  },
  {
    id: "13",
    name: "Pigment Additives",
    category: "complexion",
    price: 40,
    description: "The original listing describes oil-free color correctors to blend into foundation for a more precise color match.",
  },
  {
    id: "15",
    name: "Loose Translucent Face Powder",
    category: "complexion",
    price: 15,
    description: "Sets foundation and blends the finished makeup look for a soft, even finish.",
  },
  {
    id: "16",
    name: "Extra Oil-Controlling Loose Face Powder",
    category: "complexion",
    price: 20,
    description: "A silky loose powder with a hint of color; listed to absorb excess oil.",
  },
  {
    id: "17",
    name: "Translucent Pressed Face Powder",
    category: "complexion",
    price: 15,
    description: "A pressed finishing powder for a polished matte look and convenient touch-ups.",
  },
  {
    id: "18",
    name: "Extra Oil-Controlling Pressed Face Powder",
    category: "complexion",
    price: 20,
    description: "A pressed powder with a touch of color, described on the original site as oil-absorbing.",
  },
  {
    id: "19",
    name: "Bronzing Powder",
    category: "complexion",
    price: 15,
    description: "A warm-toned powder for adding a sun-kissed look without sun exposure.",
  },
  {
    id: "20",
    name: "Starburst Face Powder",
    category: "complexion",
    price: 20,
    description: "A corrective cover powder designed to neutralize the look of imperfections and add a subtle glow.",
  },
  {
    id: "21",
    name: "Powder Blush",
    category: "complexion",
    price: 8,
    description: "Choose a soft kiss of color or a more defined accent; contact Saint James about available shades.",
  },
  {
    id: "22",
    name: "Ultimate Powder Blush",
    category: "complexion",
    price: 12,
    description: "An elegant blush compact with brush and mirror, as described in the original product listing.",
  },
  {
    id: "23",
    name: "Powder Blush Couples",
    category: "complexion",
    price: 15,
    description: "Complementary blush shades, conveniently pre-packaged as a pair.",
  },
  {
    id: "27",
    name: "Eye Color",
    category: "eyes",
    price: 8,
    description: "A range of colors for a sheer wash or a more vivid accent.",
  },
  {
    id: "28",
    name: "Loose Eye Dust",
    category: "eyes",
    price: 12,
    description: "An opalescent loose powder for dramatic makeup and stage or theatrical looks.",
  },
  {
    id: "30",
    name: "Matte Eye Color",
    category: "eyes",
    price: 8,
    description: "Matte color with staying power; the original listing notes shades for a range of makeup looks.",
  },
  {
    id: "31",
    name: "Eye Shadow Foursomes",
    category: "eyes",
    price: 13,
    description: "Four coordinating eye-shadow colors packaged together in one compact.",
  },
  {
    id: "32",
    name: "Creme-To-Powders Shadows",
    category: "eyes",
    price: 10,
    description: "Cream eye color that blends to a smooth, soft-focus finish.",
  },
  {
    id: "34",
    name: "Eye Shadow Base",
    category: "eyes",
    price: 12,
    description: "Wear alone or underneath powder shadow for a smoother-looking base.",
  },
  {
    id: "35",
    name: "Cake Eyeliners",
    category: "eyes",
    price: 8,
    description: "A trio of popular eyeliner colors to define the eyes.",
  },
  {
    id: "36",
    name: "Liquid Eyeliners",
    category: "eyes",
    price: 9,
    description: "A quick-drying liner for a clean, defined line.",
  },
  {
    id: "37",
    name: "Waterproof Retractable Eyeliner",
    category: "eyes",
    price: 10,
    description: "A retractable liner designed for precise application, with a water-resistant formula.",
  },
  {
    id: "38",
    name: "Waterproof Retractable Brow Liners",
    category: "eyes",
    price: 10,
    description: "Retractable brow color for a subtle hint of color or more defined brows.",
  },
  {
    id: "39",
    name: "Designer Eye Pencils",
    category: "eyes",
    price: 7,
    description: "Soft pencil liners to define and emphasize the eyes.",
  },
  {
    id: "40",
    name: "Mascara",
    category: "eyes",
    price: 8,
    description: "A conditioning mascara with a spiral brush designed to separate lashes and add rich color.",
  },
  {
    id: "41",
    name: "Waterproof Mascara",
    category: "eyes",
    price: 9,
    description: "A water-resistant conditioning mascara with a spiral brush for lengthening and separation.",
  },
  {
    id: "42",
    name: "Brush Brow",
    category: "eyes",
    price: 9,
    description: "A powder brow enhancer for natural-looking definition and color.",
  },
  {
    id: "43",
    name: "Designer Lipsticks",
    category: "lips",
    price: 10,
    description: "Smooth, blendable lip color in tones ranging from creamy neutrals to shimmering golds; fortified with vitamin E.",
  },
  {
    id: "44",
    name: "Long-Lasting Matte Lipstick",
    category: "lips",
    price: 12,
    description: "A matte lipstick made for long-wearing, true color.",
  },
  {
    id: "45",
    name: "Lipstick Carousels",
    category: "lips",
    price: 25,
    description: "A collection of complementary lip colors in one case; wear individually or mix to create a custom shade.",
  },
  {
    id: "46",
    name: "Waterproof Retractable Lip Liner",
    category: "lips",
    price: 8,
    description: "A retractable lip pencil for precise definition without sharpening.",
  },
  {
    id: "47",
    name: "Lip Gloss",
    category: "lips",
    price: 12,
    description: "A glistening gloss, applied for a high-shine finish.",
  },
  {
    id: "48",
    name: "Wet Lips",
    category: "lips",
    price: 12,
    description: "A rich, glossy lip finish worn over lipstick or on bare lips.",
  },
  {
    id: "50",
    name: "Lip Pencils",
    category: "lips",
    price: 7,
    description: "Precision liners in colors selected to complement lipstick.",
  },
  {
    id: "51",
    name: "Lip Sparklettes",
    category: "lips",
    price: 18,
    description: "Gold or diamond-like sparkle to wear over lipstick or on bare lips.",
  },
  {
    id: "53",
    name: "Cleansing Milk Creme",
    category: "skincare",
    price: 20,
    description: "A gentle cleanser designed to cleanse without stripping the skin's natural moisture balance; listed for normal-to-dry skin.",
  },
  {
    id: "54",
    name: "Balancing Face Cleaner",
    category: "skincare",
    price: 16,
    description: "The original description says it removes excess oil, dirt, and makeup without the drying effects of soap.",
  },
  {
    id: "55",
    name: "Clean Eyes Make-up Remover",
    category: "skincare",
    price: 13,
    description: "A water-soluble eye makeup remover that leaves no oily residue; listed for all skin types.",
  },
  {
    id: "56",
    name: "Spearmint Aloe Masque",
    category: "skincare",
    price: 20,
    description: "A refreshing masque described as lifting dry skin cells and refining skin texture.",
  },
  {
    id: "57",
    name: "Foaming Facial Gel",
    category: "skincare",
    price: 20,
    description: "An oil-free facial cleansing gel that lathers away makeup, dirt, and oil.",
  },
  {
    id: "58",
    name: "Sea Mud Masque",
    category: "skincare",
    price: 15,
    description: "An emollient masque with natural clay and sodium hyaluronate, described as adding moisture.",
  },
  {
    id: "59",
    name: "Skin Toning Lotion",
    category: "skincare",
    price: 16,
    description: "A second-step toning lotion described as removing traces of makeup or cleanser; listed for normal-to-oily skin.",
  },
  {
    id: "60",
    name: "Non-Alcohol Toner",
    category: "skincare",
    price: 16,
    description: "An alcohol-free toner with aloe, cucumber, and lemon extracts; listed for normal-to-dry skin.",
  },
  {
    id: "62",
    name: "Skin Clarifier",
    category: "skincare",
    price: 20,
    description: "A botanical-extract astringent, described as refreshing and refining the complexion.",
  },
  {
    id: "63",
    name: "T-Zone Scrub",
    category: "skincare",
    price: 13,
    description: "A polishing scrub described as helping to smooth the skin and remove pore-clogging impurities.",
  },
  {
    id: "67",
    name: "Aloe Jojoba Creme with Vitamin E",
    category: "skincare",
    price: 15,
    description: "A lightweight moisturizer with aloe, jojoba oil, and vitamin E; listed for normal-to-oily skin.",
  },
  {
    id: "68",
    name: "Gel Facial Scrub",
    category: "skincare",
    price: 19,
    description: "An oil-free exfoliating gel with non-abrasive granules; listed for combination and oily skin types.",
  },
  {
    id: "69",
    name: "Velvet Veil",
    category: "skincare",
    price: 20,
    description: "A light lotion for softening skin or smoothing the face beneath foundation; listed for all skin types.",
  },
  {
    id: "70",
    name: "Evening Magic",
    category: "skincare",
    price: 20,
    description: "A rich nighttime moisturizer with proteins and vitamins; listed for normal-to-dry and mature skin types.",
  },
  {
    id: "71",
    name: "All Day Moisture",
    category: "skincare",
    price: 22,
    description: "A lightweight, oil-free moisturizer described as suitable for all skin types.",
  },
  {
    id: "72",
    name: "Eye Creme",
    category: "skincare",
    price: 25,
    description: "A soothing eye-area moisturizer with vitamin C; listed for all skin types.",
  },
  {
    id: "73",
    name: "Oil-Absorbing Moisturizer",
    category: "skincare",
    price: 17,
    description: "An oil-free, lightweight moisturizer described as helping to control shine; listed for combination and oily skin.",
  },
  {
    id: "74",
    name: "Vitamin C Creme SPF15",
    category: "skincare",
    price: 30,
    description: "A nourishing vitamin C moisturizer with SPF 15; listed for all skin types.",
  },
  {
    id: "90",
    name: "AHA Body Lotion",
    category: "skincare",
    price: 13,
    description: "A glycolic and fruit-acid body lotion described as helping skin retain moisture.",
  },
  {
    id: "91",
    name: "AHA Day Moisturizer Normal to Dry SPF 15",
    category: "skincare",
    price: 25,
    description: "A moisturizer with SPF 15 and glycolic and fruit acids; listed for normal-to-dry skin.",
  },
  {
    id: "92",
    name: "AHA Toner",
    category: "skincare",
    price: 16,
    description: "An alcohol-free toner with alpha hydroxy acids, listed for all skin types.",
  },
  {
    id: "93",
    name: "AHA Day Moisturizer Normal to Oily SPF 15",
    category: "skincare",
    price: 25,
    description: "A lightweight oil-free moisturizer with SPF 15 and glycolic and fruit acids; listed for normal-to-oily skin.",
  },
  {
    id: "94",
    name: "AHA Night Creme",
    category: "skincare",
    price: 24,
    description: "An overnight moisturizer with glycolic acid; listed for all skin types.",
  },
  {
    id: "95",
    name: "AHA Serum",
    category: "skincare",
    price: 35,
    description: "A concentrated alpha hydroxy acid serum; listed for all skin types.",
  },
  {
    id: "96",
    name: "AHA Cleaner Normal to Dry",
    category: "skincare",
    price: 20,
    description: "A creamy cleanser with glycolic and fruit acids; listed for normal-to-dry skin.",
  },
  {
    id: "97",
    name: "AHA Cleaner Normal to Oily",
    category: "skincare",
    price: 20,
    description: "An oil-free cleanser with glycolic and fruit acids; listed for normal-to-oily skin.",
  },
  {
    id: "98",
    name: "AHA Masque",
    category: "skincare",
    price: 24,
    description: "A facial masque with glycolic acid, described as cleansing and clarifying the complexion.",
  },
  {
    id: "99",
    name: "AHA Honey & Almond Exfoliator",
    category: "skincare",
    price: 25,
    description: "Almond meal, alpha and beta hydroxy acids, honey, and humectants in a gentle exfoliator.",
  },
  {
    id: "103",
    name: "Antioxidant Day Creme with SPF-15",
    category: "skincare",
    price: 25,
    description: "A moisturizing day creme with antioxidants and SPF 15; listed for all skin types.",
  },
  {
    id: "104",
    name: "Vitamin C Serum",
    category: "skincare",
    price: 25,
    description: "A vitamin C serum described as supporting the appearance of texture, clarity, and tone.",
  },
  {
    id: "133",
    name: "Large Artist Make-up Kit",
    category: "kits",
    price: 125,
    description: "The original listing describes a large artist kit with eye shadows, blushes, powders, foundations, lip and eye color, mirror, and applicators.",
  },
  {
    id: "134",
    name: "Small Artist Make-up Kit",
    category: "kits",
    price: 60,
    description: "The original listing describes an edit of eyes, blush, powders, lip and eye color, plus a mirror and applicators.",
  },
  {
    id: "135",
    name: "8-Piece Make-up Kit with Brush",
    category: "kits",
    price: 22,
    description: "Two blushes, four eye shadows, two lip glosses, and applicators, according to the original listing.",
  },
  {
    id: "136",
    name: "8-Piece Eyes & Face Kit with Brush",
    category: "kits",
    price: 40,
    description: "Four eye shadows and four foundations in a mirrored compact with applicator.",
  },
  {
    id: "137",
    name: "18-Piece Shadow Kit with Brush",
    category: "kits",
    price: 30,
    description: "Eighteen eye shadows and an applicator in a large mirrored compact.",
  },
  {
    id: "139",
    name: "Clear Vinyl Pouch",
    category: "accessories",
    price: 3,
    description: "A clear 5.5 × 4.75 in. pouch; accessories are not included.",
  },
  {
    id: "140",
    name: "Black Velvet Bag with Drawstring",
    category: "accessories",
    price: 4,
    description: "A 4.75 × 3 in. velvet bag with a gold drawstring; accessories are not included.",
  },
  {
    id: "141",
    name: "Cosmetic Bag with Black Drawstring",
    category: "accessories",
    price: 5,
    description: "A drawstring makeup bag in two sizes: small 5.75 × 7 in. or large 7 × 9.5 in.; accessories are not included.",
  },
  {
    id: "142",
    name: "Cosmetic Bag with Zipper",
    category: "accessories",
    price: 5,
    description: "A zippered cosmetic bag measuring 8.5 × 3.75 × 4 in.; accessories are not included.",
  },
  {
    id: "143",
    name: "Rectangular Vinyl Zipper Bag with Double Black Handles",
    category: "accessories",
    price: 8,
    description: "A rectangular 8.25 × 6.25 in. vinyl zip bag with double black handles; accessories are not included.",
  },
  {
    id: "144",
    name: "Glitter Body Gel",
    category: "extras",
    price: 7,
    description: "A sparkling body gel from the original fun-stuff collection.",
  },
  {
    id: "145",
    name: "Glitter-it",
    category: "extras",
    price: 9,
    description: "A glitter pencil for adding color and sparkle to the skin.",
  },
];

export const featuredProductIds = ["1", "30", "43", "69"] as const;
